### PR TITLE
Ft sensors cities

### PR DESCRIPTION
**Pull request by esirK**
## Description

Adds management command to reverse geocode nodes locations and update the city names for nodes with no city associated with them

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2021-02-04 at 13 48 07

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
:+1: @esirK

1. Why do we need the geo reversing in the api itself? Each function responsible of pushing data should provide correct location moving foward, right?
2. Shouldn't cities be part of location with countries in meta?

**Comment by esirK** [comment]
> 1. Why do we need the geo reversing in the api itself? Each function responsible of pushing data should provide correct location moving foward, right?
Yes moving forward we expect that. But we aren't guaranteed that will always be the case so I'm just leaving the management command here just in case anyone needs it in the future.
>Shouldn't cities be part of location with countries in meta?
I've attached the screen shot to show how it will look like. I asked @KobbyMmo before adding sensors_cities as their own object

**Comment by kilemensi** [comment]
> > Shouldn't cities be part of location with countries in meta?
> 
> I've attached the screen shot to show how it will look like. I asked @KobbyMmo before adding sensors_cities as their own object

Nah, you can't have `sensors_locations` to mean _countries_ only and have separate _sensors_cities_... either have `sensors_countries` and `sensors_cities` as standalone objects or one `sensors_locations` return `countries` and their `count` as well as `cities` and their `count`.

It should even be cities in their respective countries but it's too late for today I think.

**Comment by KobbyMmo** [comment]
Yea Isaiah, what you have will work for me

This will also be fine. 
```
location:{
      cities:{
        count: 12, data: []
      },
      countries:{
        count: 12, data: []
      }
}
```

**Comment by esirK** [comment]
@KobbyMmo  I'll stick to what we have for now. The only thing you will change is using `sensors_countries` instead of `sensors_locations`

**Review by KhadijaMahanga — APPROVED** [review]

**Pull request merged**
