### PR TITLE
Allows filtering of nodes using location city

### PR DESCRIPTION
**Pull request by esirK**
## Description
Allows Filtering of nodes using location city

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Screenshots
Screenshot 2021-02-03 at 15 17 53

Screenshot 2021-02-03 at 15 18 03

`Data`
Screenshot 2021-02-03 at 16 33 47

Screenshot 2021-02-03 at 16 33 58

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
QQ @esirK , can we may pull all the nodes and check:

1. They have cities, and
2. If we need to do any clean up to make sure names match, etc.

**Comment by esirK** [comment]
> QQ @esirK , can we may pull all the nodes and check:
> 
> 1. They have cities, and
> 2. If we need to do any clean up to make sure names match, etc.

@kilemensi not all Nodes have cities

**Comment by kilemensi** [comment]
> > QQ @esirK , can we may pull all the nodes and check:
> > 
> > 1. They have cities, and
> > 2. If we need to do any clean up to make sure names match, etc.
> 
> @kilemensi not all Nodes have cities

Do they have lat/long that we can use to reverse geocode @esirK ?

**Comment by esirK** [comment]
> > > QQ @esirK , can we may pull all the nodes and check:
> > > 
> > > 1. They have cities, and
> > > 2. If we need to do any clean up to make sure names match, etc.
> > 
> > 
> > @kilemensi not all Nodes have cities
> 
> Do they have lat/long that we can use to reverse geocode @esirK ?

I haven't seen any that's missing lat/long so yes we can do reverse geocode

**Comment by KhadijaMahanga** [comment]
> > > > QQ @esirK , can we may pull all the nodes and check:
> > > > 
> > > > 1. They have cities, and
> > > > 2. If we need to do any clean up to make sure names match, etc.
> > > 
> > > 
> > > @kilemensi not all Nodes have cities
> > 
> > 
> > Do they have lat/long that we can use to reverse geocode @esirK ?
> 
> I haven't seen any that's missing lat/long so yes we can do reverse geocode

@esirK they are a few with None

**Comment by esirK** [comment]
> > > > > QQ @esirK , can we may pull all the nodes and check:
> > > > > 
> > > > > 1. They have cities, and
> > > > > 2. If we need to do any clean up to make sure names match, etc.
> > > > 
> > > > 
> > > > @kilemensi not all Nodes have cities
> > > 
> > > 
> > > Do they have lat/long that we can use to reverse geocode @esirK ?
> > 
> > 
> > I haven't seen any that's missing lat/long so yes we can do reverse geocode
> 
> @esirK they are a few with None

In such a case, I think we will need to manually add the city.

**Comment by kilemensi** [comment]
@esirK / @KhadijaMahanga how do we even show a node on the map then?

**Comment by KhadijaMahanga** [comment]
@kilemensi  @esirK  my bad, I think they all have lat/long...the None locations don't have nodes assigned to them

**Comment by esirK** [comment]
@kilemensi  @KhadijaMahanga  I think we can merge this as I work on the reverse geocode.

**Comment by KhadijaMahanga** [comment]
Shouldn't we be filtering using lat & long instead?

**Comment by esirK** [comment]
@kilemensi  from this previous comment https://github.com/CodeForAfrica/sensors.AFRICA-api/pull/95#discussion_r567715956


> Shouldn't we be filtering using lat & long instead?

I think we want something like `v1/node?location__city=Nairobi` the same way we are doing for country

**Review by KhadijaMahanga — APPROVED** [review]

**Pull request merged**
