### PR TITLE
Ft/development env

### PR DESCRIPTION
**Pull request by thepsalmist**
## Description

Create development settings environment for separation of concerns between the production and development settings, such as the use of a database router for multiple DBs

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
I don't see any motivations to why we need separate settings in the PR description @thepsalmist .

**Comment by thepsalmist** [comment]
> I don't see any motivations to why we need separate settings in the PR description @thepsalmist .

Updated the description, but it's mainly for separation of concerns, such as the issue with migrations from feinstaub

**Comment by kilemensi** [comment]
> > I don't see any motivations to why we need separate settings in the PR description @thepsalmist .
> 
> Updated the description, but it's mainly for separation of concerns, such as the issue with migrations from feinstaub

Still don't get it @thepsalmist ... Why do we need to make this change vs. how has it been working so far? Do you mean migrations from feinstaub shouldn't happen in production?

For background, to me, what makes an environment dev or prod or whatever is the _values_ of settings which should be configurable via env vars if possible. Having a completely separate settings file signals a much bigger difference between the different environments.

**Comment by thepsalmist** [comment]
> > > I don't see any motivations to why we need separate settings in the PR description @thepsalmist .
> > 
> > 
> > Updated the description, but it's mainly for separation of concerns, such as the issue with migrations from feinstaub
> 
> Still don't get it @thepsalmist ... Why do we need to make this change vs. how has it been working so far? Do you mean migrations from feinstaub shouldn't happen in production?
> 
> For background, to me, what makes an environment dev or prod or whatever is the _values_ of settings which should be configurable via env vars if possible. Having a completely separate settings file signals a much bigger difference between the different environments.

@kilemensi this is the migration file that fails & causes the issues [https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py](url). Looking at it, Its not a typical django autogenerated migration file. We're making a READ, which from our router we're directing to our `read_replica` & yet migrations are restricted to the `default`.

**Comment by kilemensi** [comment]
> > > > I don...
> @kilemensi this is the migration file that fails & causes the [issues](https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py] ...
>

Cool @thepsalmist but I think this is to be expected. There will always be custom migrations from time to time.

Haven't tried it locally (and not sure whether the read step of the migration is completely separated from the overall migration step) but can't we use the `hints` param in the [`RunPython`](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython) method? It could be:

- `hints={'db': 'default'}`: Implies use this `db`, or the more general
- `hints={'in_migration': True}`: Implying this is happening in a migration.

The database router would then check the `hints` in `db_for_read` method and adjust accordingly.

**Comment by kilemensi** [comment]
> > > > I don...
> @kilemensi this is the migration file that fails & causes the [issues](https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py) ...
>

Another issue I've seen @thepsalmist, the custom migration [function](https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py) does not use `schema_editor` when querying the database. Compare it to the sample code in the [`docs`](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython).

Could it be the reason why a separate call is made to the database router asking it which db to use? Again, the docs are pretty insistent on using [`SchemaEditor`](https://docs.djangoproject.com/en/1.11/ref/schema-editor/#django.db.backends.base.schema.BaseDatabaseSchemaEditor) when writing custom migrations.

**Comment by thepsalmist** [comment]
> > > > > I don...
> > > > > @kilemensi this is the migration file that fails & causes the [issues](https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py) ...
> 
> Another issue I've seen @thepsalmist, the custom migration [function](https://github.com/opendata-stuttgart/feinstaub-api/blob/master/feinstaub/sensors/migrations/0011_auto_20150807_1927.py) does not use `schema_editor` when querying the database. Compare it to the sample code in the [`docs`](https://docs.djangoproject.com/en/1.11/ref/migration-operations/#django.db.migrations.operations.RunPython).
> 
> Could it be the reason why a separate call is made to the database router asking it which db to use? Again, the docs are pretty insistent on using [`SchemaEditor`](https://docs.djangoproject.com/en/1.11/ref/schema-editor/#django.db.backends.base.schema.BaseDatabaseSchemaEditor) when writing custom migrations.

The function uses query editor, specifying the db on the custom migration file as per #122 resolves the issues in this PR

**Comment by kilemensi** [comment]
Cool, lets close this then @thepsalmist

**Pull request closed without merging**
