### PR TITLE
Indexing on location fields

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

Migration files for the update done on feinstaub package on location model. (Adding index to city & country field).

An enhancement to improve performance when filtering

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
🚀 @KhadijaMahanga 

----------------------------

But before merging this (and possible deploy), shouldn't we first send Feinstaub the PR and make sure they accept it? Otherwise, we're stuck with our fork... Not  a bad think but I'd like to know what is what before moving forward.

**Comment by KhadijaMahanga** [comment]
@kilemensi alright

**Comment by KhadijaMahanga** [comment]
@kilemensi switched to opendata-stuttgart's feinstaub

**Comment by kilemensi** [comment]
Is this waiting for anything else @KhadijaMahanga ?

**Pull request merged**
